### ISSUE TITLE
0.11.0 does not start after update 0.9.0 

### ISSUE THREAD

**Issue by Beep206** [pylakey/aiotdlib#4]
Python 3.9.5

Please help what could be the problem? 

`/usr/bin/python3 "/home/user/PycharmProjects/pythonProject/venv/Bot command handler-original.py"
Traceback (most recent call last):
  File "/home/user/PycharmProjects/pythonProject/venv/Bot command handler-original.py", line 3, in <module>
    from aiotdlib import Client
  File "/usr/local/lib/python3.9/dist-packages/aiotdlib/__init__.py", line 3, in <module>
    from .client import (
  File "/usr/local/lib/python3.9/dist-packages/aiotdlib/client.py", line 30, in <module>
    from .api import (
  File "/usr/local/lib/python3.9/dist-packages/aiotdlib/api/__init__.py", line 7, in <module>
    from .api import API
  File "/usr/local/lib/python3.9/dist-packages/aiotdlib/api/api.py", line 10, in <module>
    from .functions import *
  File "/usr/local/lib/python3.9/dist-packages/aiotdlib/api/functions/__init__.py", line 57, in <module>
    from .click_animated_emoji_message import ClickAnimatedEmojiMessage
ModuleNotFoundError: No module named 'aiotdlib.api.functions.click_animated_emoji_message'

Process finished with exit code 1`

**Comment by pylakey** [comment]
There were some lost functions when TDLib was upgraded to 1.7.8. 

Should be fixed in [0.11.2](https://github.com/pylakey/aiotdlib/releases/tag/0.11.2)
